required = [
    "github.com/eclipse/paho.mqtt.golang",
    "github.com/BurntSushi/toml",
    "github.com/robvanbentem/gogarden",
    "github.com/robvanbentem/gocmn",
    "github.com/go-sql-driver/mysql",
]
